/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DatabaseStatus = IDL.Record({
  'drugbank' : IDL.Bool,
  'kegg' : IDL.Bool,
  'ncbi' : IDL.Bool,
  'pubchem' : IDL.Bool,
  'uniprot' : IDL.Bool,
});
export const SearchHistoryEntry = IDL.Record({
  'drugsFound' : IDL.Nat,
  'diseaseName' : IDL.Text,
  'timestamp' : IDL.Int,
  'pathwaysFound' : IDL.Nat,
});
export const Pathway = IDL.Record({
  'id' : IDL.Text,
  'source' : IDL.Text,
  'keggId' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'confidenceScore' : IDL.Nat,
});
export const DrugRecommendation = IDL.Record({
  'id' : IDL.Text,
  'pubchemId' : IDL.Text,
  'drugbankId' : IDL.Text,
  'name' : IDL.Text,
  'mechanismOfAction' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'approvalStatus' : IDL.Text,
  'targetProteinId' : IDL.Text,
});
export const ProteinTarget = IDL.Record({
  'id' : IDL.Text,
  'function' : IDL.Text,
  'pathwayId' : IDL.Text,
  'name' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'uniprotId' : IDL.Text,
  'geneName' : IDL.Text,
});
export const DiseaseResult = IDL.Record({
  'ncbiDiseaseId' : IDL.Opt(IDL.Text),
  'pathways' : IDL.Vec(Pathway),
  'totalConfidence' : IDL.Nat,
  'diseaseName' : IDL.Text,
  'searchTimestamp' : IDL.Int,
  'drugs' : IDL.Vec(DrugRecommendation),
  'proteins' : IDL.Vec(ProteinTarget),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getDatabaseStatus' : IDL.Func([], [DatabaseStatus], ['query']),
  'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchHistoryEntry)], ['query']),
  'getSuggestedDiseases' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'searchDisease' : IDL.Func([IDL.Text], [DiseaseResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DatabaseStatus = IDL.Record({
    'drugbank' : IDL.Bool,
    'kegg' : IDL.Bool,
    'ncbi' : IDL.Bool,
    'pubchem' : IDL.Bool,
    'uniprot' : IDL.Bool,
  });
  const SearchHistoryEntry = IDL.Record({
    'drugsFound' : IDL.Nat,
    'diseaseName' : IDL.Text,
    'timestamp' : IDL.Int,
    'pathwaysFound' : IDL.Nat,
  });
  const Pathway = IDL.Record({
    'id' : IDL.Text,
    'source' : IDL.Text,
    'keggId' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'confidenceScore' : IDL.Nat,
  });
  const DrugRecommendation = IDL.Record({
    'id' : IDL.Text,
    'pubchemId' : IDL.Text,
    'drugbankId' : IDL.Text,
    'name' : IDL.Text,
    'mechanismOfAction' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'approvalStatus' : IDL.Text,
    'targetProteinId' : IDL.Text,
  });
  const ProteinTarget = IDL.Record({
    'id' : IDL.Text,
    'function' : IDL.Text,
    'pathwayId' : IDL.Text,
    'name' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'uniprotId' : IDL.Text,
    'geneName' : IDL.Text,
  });
  const DiseaseResult = IDL.Record({
    'ncbiDiseaseId' : IDL.Opt(IDL.Text),
    'pathways' : IDL.Vec(Pathway),
    'totalConfidence' : IDL.Nat,
    'diseaseName' : IDL.Text,
    'searchTimestamp' : IDL.Int,
    'drugs' : IDL.Vec(DrugRecommendation),
    'proteins' : IDL.Vec(ProteinTarget),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getDatabaseStatus' : IDL.Func([], [DatabaseStatus], ['query']),
    'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchHistoryEntry)], ['query']),
    'getSuggestedDiseases' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'searchDisease' : IDL.Func([IDL.Text], [DiseaseResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };