/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DrugRecommendation {
    id: string;
    pubchemId: string;
    drugbankId: string;
    name: string;
    mechanismOfAction: string;
    confidenceScore: bigint;
    approvalStatus: string;
    targetProteinId: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Pathway {
    id: string;
    source: string;
    keggId: string;
    name: string;
    description: string;
    confidenceScore: bigint;
}
export interface DiseaseResult {
    ncbiDiseaseId?: string;
    pathways: Array<Pathway>;
    totalConfidence: bigint;
    diseaseName: string;
    searchTimestamp: bigint;
    drugs: Array<DrugRecommendation>;
    proteins: Array<ProteinTarget>;
}
export interface DatabaseStatus {
    drugbank: boolean;
    kegg: boolean;
    ncbi: boolean;
    pubchem: boolean;
    uniprot: boolean;
}
export interface SearchHistoryEntry {
    drugsFound: bigint;
    diseaseName: string;
    timestamp: bigint;
    pathwaysFound: bigint;
}
export interface ProteinTarget {
    id: string;
    function: string;
    pathwayId: string;
    name: string;
    confidenceScore: bigint;
    uniprotId: string;
    geneName: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface backendInterface {
    getDatabaseStatus(): Promise<DatabaseStatus>;
    getSearchHistory(): Promise<Array<SearchHistoryEntry>>;
    getSuggestedDiseases(): Promise<Array<string>>;
    searchDisease(diseaseName: string): Promise<DiseaseResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { DiseaseResult as _DiseaseResult, DrugRecommendation as _DrugRecommendation, Pathway as _Pathway, ProteinTarget as _ProteinTarget } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getDatabaseStatus(): Promise<DatabaseStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getDatabaseStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDatabaseStatus();
            return result;
        }
    }
    async getSearchHistory(): Promise<Array<SearchHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSearchHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSearchHistory();
            return result;
        }
    }
    async getSuggestedDiseases(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestedDiseases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestedDiseases();
            return result;
        }
    }
    async searchDisease(arg0: string): Promise<DiseaseResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDisease(arg0);
                return from_candid_DiseaseResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDisease(arg0);
            return from_candid_DiseaseResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_DiseaseResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiseaseResult): DiseaseResult {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ncbiDiseaseId: [] | [string];
    pathways: Array<_Pathway>;
    totalConfidence: bigint;
    diseaseName: string;
    searchTimestamp: bigint;
    drugs: Array<_DrugRecommendation>;
    proteins: Array<_ProteinTarget>;
}): {
    ncbiDiseaseId?: string;
    pathways: Array<Pathway>;
    totalConfidence: bigint;
    diseaseName: string;
    searchTimestamp: bigint;
    drugs: Array<DrugRecommendation>;
    proteins: Array<ProteinTarget>;
} {
    return {
        ncbiDiseaseId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.ncbiDiseaseId)),
        pathways: value.pathways,
        totalConfidence: value.totalConfidence,
        diseaseName: value.diseaseName,
        searchTimestamp: value.searchTimestamp,
        drugs: value.drugs,
        proteins: value.proteins
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
